spring:
  application:
    name: Book_accounting_service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
